Feature/whats new
ApplETS/Portal-API pull request #5
Opened 2022-03-26 04:37 UTC by JonathanDuvalV

2022-03-26 05:37 UTC, MysticFragilist requested changes
Alsooo, veux pas être trop gossant maiiiis faudrait faire des tests sur les fonctions 😄 j't'aiderai si tu veux, ça sera pas trop long!

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Controllers/ProjectController.cs
> +    }
T'en penses quoi de déplacer ça dans les première fonctions de la classe (après le constructeur)? Juste parce que c'est conventionnel de mettre les GET en premier :) c'est pas très grave non plus sinon

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Models/DTOs/ProjectCreationDTO.cs
> +	public string? CurrentVersion { get; set; }
Il y a certains fields qui ont plus de tabs que d'autres je sais pas si c'est à cause de github ou si c'est comme ça dans le code faudrait vérifier!

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Models/DTOs/ProjectDTO.cs
> +	public string? CurrentVersion { get; set; }
idem

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Repos/Abstractions/IProjectRepository.cs
> +	public Task Create(Project project);
idem

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Services/ProjectService.cs
> +}
Faudrait pt mettre les crud what's new dans un service à part, t'en pense quoi?

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Models/FirestoreModels/WhatsNew.cs
> +}
On a pas besoin d'id sur ces models là?

2022-03-26 05:37 UTC, MysticFragilist commented on WhatsNewApi/Models/FirestoreModels/WhatsNewPage.cs
> +}
idem l'id pour la WhatsNewPage?

2022-03-26 17:20 UTC, JonathanDuvalV commented
> Alsooo, veux pas être trop gossant maiiiis faudrait faire des tests sur les fonctions 😄 j't'aiderai si tu veux, ça sera pas trop long!

Yees my bad! J'y ai pas pensé en faisant la PR hier soir, jetais un peu dead et ca ma sorti de la tete. Je les fait cette semaine!

2022-03-26 17:27 UTC, JonathanDuvalV commented
@MysticFragilist 
Pour les CRUDs de WhatsNew, j'étais pas trop certains de où les placer vue que sur Firestore les objets WhatsNew sont dans les Projects. Mais ouais un service à part serait surement mieux! Pareil pour les IDs, les 2 objets de WhatsNew en ont pas vue qui sont dans les projets.
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/45638733/160250505-145d7a1b-af75-45f0-b337-c95110dd173a.png">

So pour les objets WhatsNew, d'après toi faudrais tu les retirer de l'objet projet, les mettre dans une collection a part et rajouter un field ProjectId dessus pour garder un lien? Comme ca y'aurait leur propre ID et au lieu d'utiliser la version pour aller les fetchs, on pourrait utiliser leur ID

2022-03-27 02:16 UTC, MysticFragilist commented
> @MysticFragilist Pour les CRUDs de WhatsNew, j'étais pas trop certains de où les placer vue que sur Firestore les objets WhatsNew sont dans les Projects. Mais ouais un service à part serait surement mieux! Pareil pour les IDs, les 2 objets de WhatsNew en ont pas vue qui sont dans les projets. <img alt="image" width="1125" src="https://user-images.githubusercontent.com/45638733/160250505-145d7a1b-af75-45f0-b337-c95110dd173a.png">
> 
> So pour les objets WhatsNew, d'après toi faudrais tu les retirer de l'objet projet, les mettre dans une collection a part et rajouter un field ProjectId dessus pour garder un lien? Comme ca y'aurait leur propre ID et au lieu d'utiliser la version pour aller les fetchs, on pourrait utiliser leur ID

Yesss ça serait parfait je pense! :) comme ça on dissocie les what's new des projets (Les projets vont peut-être servir à linker autre chose genre firebase crashlytics et tout)

2022-03-28 14:23 UTC, JonathanDuvalV commented on WhatsNewApi/Models/DTOs/ProjectCreationDTO.cs
> +	public string? CurrentVersion { get; set; }
Hmm moi de mon bord dans le code sont chill, github ou visual studio de mac est sur le crack

2022-03-28 15:34 UTC, JonathanDuvalV commented on WhatsNewApi/Models/FirestoreModels/WhatsNewPage.cs
> +}
J'ai ajouté un ID sur WhatsNew mais pour les pages je crois pas c'est nécessaire vue que c'est un tableau dans l'objet WhatsNew right? Tant qu'a faire du NoSQL aussi bien en profiter ahaha

2022-03-28 15:34 UTC, JonathanDuvalV commented on WhatsNewApi/Models/FirestoreModels/WhatsNewPage.cs
> +}
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/45638733/160434283-b2541e1f-6572-4b4f-b6b8-5543ffb45833.png">

2022-03-28 15:35 UTC, JonathanDuvalV commented
Manque juste les tests, je fais ca cette semaine! @MysticFragilist si tu vx me confirmer que le reste est chill avant que je les fasses

2022-03-28 15:59 UTC, MysticFragilist requested changes
Sorry quelques autres trucs, mais les changes que t'avais fait sont good! :100:

2022-03-28 15:59 UTC, MysticFragilist commented on WhatsNewApi/Controllers/ProjectController.cs
> +    [HttpGet("{projectId}")]
Ahh il y a ça que j'avais pas vu je crois, mais je pense que ça serait pertinent qu'il y aille un allow anonymous sur le get project aussi. La raison est simple, c'est qu'on a besoin de l'id pour accéder au get de la version what's new en mode anonyme. T'en penses quoi?

2022-03-28 15:59 UTC, MysticFragilist commented on WhatsNewApi/Controllers/ProjectController.cs
> +    [HttpGet]
Peut-être ici aussi j'imagine. De toute façon le nom et id des projets à pas besoin d'être sécurisé.

2022-03-28 15:59 UTC, MysticFragilist commented on WhatsNewApi/Models/FirestoreModels/WhatsNewPage.cs
> +}
> J'ai ajouté un ID sur WhatsNew mais pour les pages je crois pas c'est nécessaire vue que c'est un tableau dans l'objet WhatsNew right? Tant qu'a faire du NoSQL aussi bien en profiter ahaha

Yes je suis d'accord, ils seraient directement dans what's new

2022-03-28 15:59 UTC, MysticFragilist commented on WhatsNewApi/Services/WhatsNewService.cs
> +        public async Task<WhatsNew> GetWhatsNew(string projectId, string version)
Ok pour ça sorry j'avais pas review 😅 mais le service devrait retourner la version de what's new ainsi que toute les versions supérieures. En gros, ce que je conseille c'est de grab toutes les versions supérieur à la valeur passée dans le get et de concaténer toutes les pages pour faire une seule grosse liste que tu retourne dans le premier what's new. 

De cette manière là, si un user skip l'update d'une version tu viens de forcer le user à voir tous les what's new entre sa version précédente et la nouvelle version de l'appli.

Y'aurait moyen de provide un paramètre `unique` pour faire ce que tu fais en ce moment si jamais! Ça pourrait être pratique dans certain cas.

Si jamais on pourrait se call si t'as des questions sur le behavior :smile:

2022-03-28 16:08 UTC, JonathanDuvalV commented on WhatsNewApi/Services/WhatsNewService.cs
> +        public async Task<WhatsNew> GetWhatsNew(string projectId, string version)
Peut-etre je garderais pareil cette méthode la et faire une route et une méthode différente dans le service pour behaviour que tu décris. Vue que sur le portail, mettons qu'on veut edit un whats new d'une version spécifique faut qu'on soit en mesure de get juste les pages de celui qu'on veut edit et pas genre une concaténation de toute les versions précédentes.

mettons la route serait "{version}/uptodate" ou dequoi du genre. T'en pense quoi?

2022-03-28 16:09 UTC, JonathanDuvalV commented on WhatsNewApi/Controllers/ProjectController.cs
> +    [HttpGet("{projectId}")]
Ouais makes sense!

2022-03-28 16:13 UTC, JonathanDuvalV commented on WhatsNewApi/Services/WhatsNewService.cs
> +        public async Task<WhatsNew> GetWhatsNew(string projectId, string version)
En vrai j'ai rien dit, pour le portail la liste va être rempli avec le GetAll et quand on ouvre le modal pour edit on va deja avoir les valeurs a cause du GetAll so pas besoin d'une route pour ca je crois

2022-06-14 00:27 UTC, JonathanDuvalV commented
@MysticFragilist Y manque encore quelque tests dans certaines fonctions qui ont de la logique. J'avais commencer a faire les tests pour le VersionController et je penses pas que c'est worth en faire pour les CRUD operations basics mais si tu veux le 100% de coverage je peux les faire aussi.

2022-06-17 01:07 UTC, MysticFragilist approved these changes
Goood jooob pour les tests! Quelques petits trucs mais sinon c'est bon! Pour les suggestions tu peux les commits directe c'est des ptit fix au niveaux des tab/space et du format. 😄 

Sinon tu disais que les tests il te manquait dequoi à tester, ça fait un coverage de combien maintenant?

2022-06-17 01:07 UTC, MysticFragilist commented on test/Mock/Constants.cs
> +	public static class Constants
Bonne idée pour ce fichier là, ça va aider à séparer les data qu'on attends. Quand on en aura plus on regardera pour les séparer en sous fichier pour améliorer la lisibilité, mais pour tout  de suite c'est good! 😄

2022-06-17 01:08 UTC, MysticFragilist requested changes
^^ comments above

2022-06-22 22:12 UTC, JonathanDuvalV commented
> Goood jooob pour les tests! Quelques petits trucs mais sinon c'est bon! Pour les suggestions tu peux les commits directe c'est des ptit fix au niveaux des tab/space et du format. 😄
> 
> Sinon tu disais que les tests il te manquait dequoi à tester, ça fait un coverage de combien maintenant?

Bonne question pour le coverage j'arrive pas a le voir sur VS de mac 😅 Sinon en gros y manque les tests pour les controllers mais je vois pas vraiment la pertinence pour.. Same pour le FirebaseService, ca fait basically juste utiliser un nuget de Google ya pas grand chose worth a tester et ProjectService je vais faire un test live pour le UpdateVersion vue que c'est le seul qui a vraiment de la logique, le reste des methodes cest les CRUDs de base

2022-08-05 13:42 UTC, MysticFragilist approved these changes
LGTM!

2022-08-05 13:44 UTC, merged